---
require:
  - rubocop-rspec

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Rspec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  MaxNesting: 7

RSpec/StubbedMock:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9
