---
require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.0

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Rspec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/StubbedMock:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false